name: Sync Labels

on:
  push:
    paths:
      - .github/labels.yaml

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}